# NumPy

- Es una extencion de Python para trabajar con vectores y matrices
- Es una libreria de algebra Lineal muy rapida
- Es bastante recomendable instalar Python utilizando la distribucion anaconda
- Si tienes instalado la distribucion de Anaconda, para instalar Numpy solo tienes que ir a la terminal de comandos y ejecutar
      conda intall numpy
- Si no tienes instalado anaconda, puedes instalar Numpy en la terminal de comandos mediante la ejecucion del siguiente comando
      pip install numpy
 - Para este curso utilizares Numpy para trabajar con arrays
 - Los vectores son arryas de 1 dimencion
 - Las matrices son arrays de 2 dimenciones (1 o mas filas y 1 o mas columnas)

In [1]:
import numpy as np 

In [2]:
lista = [1,2,3,4,5,6,7,8,9,10]

In [4]:
array= np.array(lista) # Array de una sola dimencion
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
lista2 = [[1,2,3],[4,5,6],[7,8,9]]
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
array2Dimen = np.array(lista2) # Creamos un array de dos dimenciones
array2Dimen 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Numpy arrays - arange, zeros, ones. linespace, eye

In [11]:
import numpy as np

array = np.arange(5) # Creamos un array con un rango de 0 a 5
array

np.arange(2,10) # Creamos un arya que comienza en 2 y termina en 9

np.arange(2,20,2) # Creamos un arya que comienza en 2 y termina en 9, pero aumentando de 2 en 2


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

Metodo zeros

In [13]:
np.zeros(3) # Genera un array de una sola dimension de 3 elementos de 0's

np.zeros((3,4)) # Dos corchetes = dos dimensiones (3 filas y 4 columnas)



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(5) # Creamos un vector de una dimencion con unos

array([1., 1., 1., 1., 1.])

In [17]:
# El doble parentesis indica que es una matris
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(5,8,50) # Una matris que crea 50 elementos entre el 5 y el 8

np.linspace(3,9,10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [20]:
np.eye(5) # Creamos una matriz cuadrada donde la diagonal es 1's (5 filas y 5 columnas)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.eye(10) # La diagonal de unos

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Numpy arrays - Numeros aleatorios - rand randn

In [23]:
import numpy as np

np.random.rand(5) # Genera 5 elementos que van a ahcer aleatorios ente 0 y 5


array([0.77584464, 0.53608385, 0.35904988, 0.51350336, 0.98290561])

In [24]:
np.random.rand(2,3) # Lo creamos de dos dimenciones 2 filas y 3 columbas con numeros entre 0 y 1

array([[0.34362075, 0.26366707, 0.72870361],
       [0.47271942, 0.55102066, 0.60341881]])

In [25]:
np.random.randn(4) # Genera 4 elementos con numeros positivos y negativos

array([-0.02953984, -0.30758007,  1.20123058, -0.53089154])

In [26]:
np.random.randn(4,3) # Matris de 4 filas y 3 columnas 

array([[ 0.16359392, -0.60505837,  0.16454584],
       [ 1.58366951, -0.74164116,  1.20613543],
       [-0.03532935, -0.93944668, -0.07125555],
       [ 0.97070465,  0.58205552,  0.47430008]])

# Numpy arrays - Numeros aleatorios enteros, randint

In [27]:
import numpy as np


In [28]:
np.random.randint(1,11) # Genera numeros enteros entre 1 y 10

9

In [29]:
np.random.randint(1,11,5) # Un array de numeros enteros pero solo de 5 elementos entre 1 y 10

array([9, 4, 7, 1, 7])

# Numpy arrays - reshape
Permite cambiar el tamaño de los arrys

In [30]:
import numpy as np

In [31]:
array = np.random.randint(1,100,25)

In [32]:
array

array([74, 64, 63, 25, 36, 40, 42,  9, 35, 93, 38, 52, 42, 56, 86,  9, 77,
       98, 93, 98, 90, 89,  2, 36, 50])

In [35]:
matriz = array.reshape(5,5) # CAmbiamos el array a un vector pero el numero  filas = columnas
# Con la misma cantidad de elementos que tiene el array (25 = 5 * 5)
matriz

array([[74, 64, 63, 25, 36],
       [40, 42,  9, 35, 93],
       [38, 52, 42, 56, 86],
       [ 9, 77, 98, 93, 98],
       [90, 89,  2, 36, 50]])

# Numpy arrays - max y min

In [36]:
array =  np.random.randint(1,100,50)
array

array([32, 20,  6, 69, 49, 76, 36, 60, 92, 13, 39, 63,  4, 68, 32, 96, 84,
       62,  2, 59, 87, 46,  5,  4, 53, 90, 26, 29, 68, 74, 95, 77, 69, 70,
       39, 78, 79, 29, 74, 89, 59, 50, 54, 63, 79, 63, 43, 81, 52, 54])

Para conocer la posicion del valor minimo y maximo lo hacemos con la siguiente expresion

In [38]:
valor_max = array.max() # Obtenemos el valor maximo del array
valor_max

96

In [39]:
# para conocer la poscion del valor maximo
posicion_valor_max = array.argmax()
posicion_valor_max

15

In [40]:
valor_min = array.min() # Obtneos el valor minimo
valor_min

2

In [41]:
posicion_valor_min = array.argmin()
posicion_valor_min # Obtnemos la posicion del valor minimo

18

# Arrays von una dimension

In [42]:
import numpy as np


In [44]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Indexacion es poder ingrresar a cada elemento de forma individual

In [45]:
array[0]

0

In [46]:
array[7]

7

In [47]:
array[-1]

9

In [48]:
array[2:4] # Muestre los elementos desde la posicion 2 hasta la 4

array([2, 3])

In [49]:
array[2:] # Muestre desde la posicion 2 en adelante

array([2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
array[:5] # Desde la posicion 5 hacia atras

array([0, 1, 2, 3, 4])

In [51]:
array2 = array.copy() # Copiamos el array1 en el array2
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
array2[0] = 100
array2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

# Arrays de Dos Dimensiones

In [54]:
import numpy as np

In [57]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
matriz[0]

array([1, 2, 3])

In [59]:
matriz[0:2] # selecciona las dos primeras filas

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
matriz[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
matriz[0][2]

3

In [62]:
matriz[1][2]

6

In [63]:
matriz[1,2]

6

In [64]:
matriz[2,2]

9

In [68]:
matriz[:,:0]

array([], shape=(3, 0), dtype=int32)

In [67]:
matriz[:,:2] # las dos primera columnas

array([[1, 2],
       [4, 5],
       [7, 8]])

# Seleccion por condicion

Numpy - Seleccionar elementos de un array segun una condicion

In [69]:
import numpy as np

In [72]:
array = np.arange(0,16)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [76]:
condicion = array > 5
condicion # Muestra un array booleano donde indica los elementos que cumplen la condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [80]:
array[condicion]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [81]:
array[array > 5] # Los elementos que sean mayores a 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [82]:
array_pares = array[array  % 2 == 0]
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14])

# Operaciones sobre arrays

In [83]:
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
array_suma= array + array
array_suma

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [85]:
array_mult = array * 100 # Multiplicamos por 100 cada elemento del array por 100
array_mult

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [86]:
# Podemos cualquier tipo de operacion sobre los elementos de un array

In [87]:
np.sqrt(array) # sacamos la raiz cuadrada a cada elemento del array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])


# Ejercicio # 1

Crear una lista de numeros secuenciales con el valor minimo de 10 y el valor maximo 
convierte esta lista en una lista o matri de 2 dimenciones (3 filas por 10 columnas)
Muestre en panatalla el valor del elemento de la esquina superior derecha de la matriz

In [94]:
array =  np.arange(10,40)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [95]:
matriz = array.reshape(3,10)
matriz

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [99]:
matriz[0][9]

19